import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";
import { defineConfig, globalIgnores } from "eslint/config";
import eslintConfigPrettier from "eslint-config-prettier";

export default defineConfig([
  globalIgnores([
    "dist",
    "dist-cli",
    "dist-lib",
    "dist-ssr",
    "coverage",
    "coverage-all",
    "build",
    "numbl_test_scripts",
    "tmp",
    // Generated by scripts/build_runtime_snippets.ts.
    "src/numbl-core/jit/builtins/runtime/snippets.gen.ts",
  ]),
  {
    files: ["**/*.{ts,tsx}"],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
      eslintConfigPrettier,
    ],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
  },
  // Vendored JIT compiler (src/numbl-core/jit). Pure compiler code, not
  // React: helper functions like `useRuntime` / `useRuntimeByName` trip
  // the React-hooks naming heuristic, and the modules export non-component
  // values. Disable the React-only rules here; all other lint rules stay.
  {
    files: ["src/numbl-core/jit/**/*.{ts,tsx}"],
    rules: {
      "react-hooks/rules-of-hooks": "off",
      "react-refresh/only-export-components": "off",
    },
  },
]);
